spring.application.name=library
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
jwt.key=bXlfc3VwZXJfc2VjdXJlX2FuZF9sb25nX2tleV8xMjM0NTY3ODkw
apiPrefix=/api/v1
jwt.expiration=3600
user.expiration=2592000
